In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

age  gender   review education purchased
21   32    Male  Average        PG        No
28   48    Male     Poor    School        No
42   30  Female     Good        PG       Yes
19   97    Male     Poor        PG       Yes
39   76    Male     Poor        PG        No

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],
                                                 df.iloc[:,-1],test_size=0.2)

In [8]:
X_train

review education
37  Average        PG
7      Poor    School
35     Poor    School
28     Poor    School
2      Good        PG
25     Good    School
38     Good    School
5   Average    School
39     Poor        PG
42     Good        PG
10     Good        UG
41     Good        PG
48     Good        UG
11     Good        UG
9      Good        UG
6      Good    School
8   Average        UG
49     Good        UG
23     Good    School
34  Average    School
36     Good        UG
29  Average        UG
40     Good    School
0   Average    School
17     Poor        UG
16     Poor        UG
12     Poor    School
33     Good        PG
18     Good    School
24  Average        PG
47     Good        PG
31     Poor    School
13  Average    School
14     Poor        PG
20  Average    School
26     Poor        PG
27     Poor        PG
45     Poor        PG
4   Average        UG
22     Poor        PG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
#ordinal encoding will be performed because these columns have ordinal data
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [13]:
X_train

array([[1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.]])

In [14]:
X_test

array([[0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [1., 1.]])

In [15]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [16]:
from sklearn.preprocessing import LabelEncoder

In [26]:
#Label encoding is performed as it is output column and have categorical data
#no parameters so it'll decide random values
le = LabelEncoder()

In [20]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [22]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [23]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [24]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1])